mmtMVC/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mmtMVC.Models;
using System.Xml;
using System.Xml.Linq;

namespace mmtMVC.Controllers
{
    public class SectionsController : Controller
    {
        private MMT_ConstEntities db = new MMT_ConstEntities();

        // GET: Sections
        public ActionResult Listing(int? eid)
        {

            if (eid != null)
            {
                Session["examid"] = eid;
            }
            else
            {
                if (Session["examid"] != null)
                {
                    eid = (int)Session["examid"];
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }



            ViewBag.ErrorMessage = TempData["ErrorMessage"] as string;
            var mmtsections = (from e in db.mmtsections where e.examid == eid select e).AsEnumerable();

            bool has = mmtsections.Any(mmtsection => mmtsection.sectionname == "-----");
            if (has == true)
            {
                ViewBag.NextButton = false;

            }
            else
            {
                ViewBag.NextButton = true;
            }


            return View(mmtsections.ToList());
        }

        // GET: Sections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mmtsection mmtsection = db.mmtsections.Find(id);

            if (mmtsection.sectionname == "-----")
            {
                mmtsection.sectionname = "";
                mmtsection.configured = false;
            }
            else
            {
                mmtsection.configured = true;
            }

            if (mmtsection == null)
            {
                return HttpNotFound();
            }
            return View(mmtsection);
        }


        // POST: Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create()
        {

            if (Session["examid"] == null)
            {

            }
            string vartxtSectionName = "-----";
            int sectioncount = 0;
            string vartxtDesc = "";
            string vartxtTime = "00:00:00";
            string vardrpShowintro = "0";
            string vardrpSectionTitle = "1";
            string vardrpMark = "1";
            string vardrpReview = "0";
            string vardrpQuesCompu = "0";
            string vardrpOptRandom = "0";
            mmtexam std = null;
            using (var c = new MMT_ConstEntities())
            {
                int eid = Convert.ToInt32(Session["examid"]);
                sectioncount = (from e in c.mmtsections where e.examid == eid select e).Count();
                sectioncount++;

                std = (from s in db.mmtexams
                       where s.examid == eid
                       select s).FirstOrDefault<mmtexam>();

            }

            string value = Request.Form["ddlsections"];
            if (value != "")
            {
                mmtsection section = new mmtsection();

                if (value == "1")
                {
                    section.type = type.MCQ;

                }
                else if (value == "6")
                {
                    section.type = type.SUBJECTIVE;

                }
                else
                {
                    section.type = type.CODEASSESS;

                }

                section.examid = (int)Session["examid"];
                section.sectionname = "-----";
                section.sectionid = sectioncount;
                section.active = true;
                db.mmtsections.Add(section);
                db.SaveChanges();
                int secid = section.secid;



                XmlNode xmlRoot;
                XmlDocument xmldoc = new XmlDocument();
                xmldoc.LoadXml(std.masterxmlfile);
                xmlRoot = xmldoc.SelectSingleNode("//test//sections");


                XmlElement sectionx = xmldoc.CreateElement("section");
                sectionx.InnerText = "";
                xmlRoot.AppendChild(sectionx);

                XmlAttribute xmlsectionId = xmldoc.CreateAttribute("id");
                xmlsectionId.Value = sectioncount.ToString();
                sectionx.Attributes.Append(xmlsectionId);

                XmlAttribute sectype = xmldoc.CreateAttribute("type");
                sectype.Value = value;
                sectionx.Attributes.Append(sectype);

                XmlAttribute auto = xmldoc.CreateAttribute("auto");
                auto.Value = "0";
                sectionx.Attributes.Append(auto);

                XmlAttribute xmlcount = xmldoc.CreateAttribute("count");
                xmlcount.Value = "";
                sectionx.Attributes.Append(xmlcount);

                XmlAttribute xmlintro = xmldoc.CreateAttribute("showintro");
                xmlintro.Value = vardrpShowintro;
                sectionx.Attributes.Append(xmlintro);

                XmlAttribute xmltitle = xmldoc.CreateAttribute("showtitle");
                xmltitle.Value = vardrpSectionTitle;
                sectionx.Attributes.Append(xmltitle);

                XmlAttribute xmlmark = xmldoc.CreateAttribute("showmark");
                xmlmark.Value = vardrpMark;
                sectionx.Attributes.Append(xmlmark);

                XmlAttribute xmlreview = xmldoc.CreateAttribute("showreview");
                xmlreview.Value = vardrpReview;
                sectionx.Attributes.Append(xmlreview);

                XmlAttribute xmlvarquestioncompulsory = xmldoc.CreateAttribute("questioncompulsory");
                xmlvarquestioncompulsory.Value = vardrpQuesCompu;
                sectionx.Attributes.Append(xmlvarquestioncompulsory);

                XmlAttribute xmlvarqrandom = xmldoc.CreateAttribute("randomizeoptions");
                xmlvarqrandom.Value = vardrpOptRandom;
                sectionx.Attributes.Append(xmlvarqrandom);

                string negscore = "0";

                //if (DropDownList1.SelectedValue == "1")
                //{
                //    negscore = txtnegative.Text;
                //}

                XmlAttribute isnegative = xmldoc.CreateAttribute("isnegative");
                //   isnegative.Value = DropDownList1.SelectedValue;
                isnegative.Value = "0";
                sectionx.Attributes.Append(isnegative);

                XmlAttribute negativescore = xmldoc.CreateAttribute("negativescore");
                negativescore.Value = negscore;
                sectionx.Attributes.Append(negativescore);


                XmlElement vartitle = xmldoc.CreateElement("section_title");
                vartitle.InnerText = vartxtSectionName;
                sectionx.AppendChild(vartitle);

                XmlElement vardescsec = xmldoc.CreateElement("section_description");
                vardescsec.InnerText = vartxtDesc;
                sectionx.AppendChild(vardescsec);

                XmlElement vartime1 = xmldoc.CreateElement("Time");
                if (value == "8")
                {

                    vartime1.InnerText = "00:00:00";

                }
                else
                {

                    vartime1.InnerText = vartxtTime;

                }

                if (value == "3")
                {
                    XmlAttribute rectime = xmldoc.CreateAttribute("rectime");
                    rectime.Value = "";
                    vartime1.Attributes.Append(rectime);
                }

                sectionx.AppendChild(vartime1);

                XmlElement quesratio = xmldoc.CreateElement("QuestionRatio");
                quesratio.InnerText = "";
                sectionx.AppendChild(quesratio);

                XmlAttribute sttype = xmldoc.CreateAttribute("type");
                sttype.Value = "1";
                quesratio.Attributes.Append(sttype);

                XmlAttribute secstatus = xmldoc.CreateAttribute("status");
                secstatus.Value = "";
                quesratio.Attributes.Append(secstatus);

                XmlAttribute seclevel1 = xmldoc.CreateAttribute("level1");
                seclevel1.Value = "";
                quesratio.Attributes.Append(seclevel1);

                XmlAttribute seclevel2 = xmldoc.CreateAttribute("level2");
                seclevel2.Value = "";
                quesratio.Attributes.Append(seclevel2);

                XmlAttribute seclevel3 = xmldoc.CreateAttribute("level3");
                seclevel3.Value = "";
                quesratio.Attributes.Append(seclevel3);

                XmlAttribute secquestioncount = xmldoc.CreateAttribute("questioncount");
                secquestioncount.Value = "";
                quesratio.Attributes.Append(secquestioncount);

                XmlElement topics = xmldoc.CreateElement("topics");
                topics.InnerText = "";
                sectionx.AppendChild(topics);

                mmttopic checktop = (from t in db.mmttopics
                                     where t.examid != section.examid && t.secid == section.secid
                                     select t).FirstOrDefault<mmttopic>();
                if (checktop == null)
                {
                    mmttopic newtopic = new mmttopic();
                    newtopic.topicname = "New Topic";
                    newtopic.secid = section.secid;
                    newtopic.sectionid = section.sectionid ?? 0;
                    newtopic.examid = section.examid ?? 0;
                    newtopic.active = true;

mmtMVC/Views/Sections/Listing.cshtml
@model IEnumerable<mmtMVC.Models.mmtsection>

@{
    ViewBag.Title = "Section Listing";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<style>
    .score_tbl th, td {
        padding-bottom: 10px;
        padding-top: 10px;
    }

    .creation_listing td {
        padding-left: 10px;
        text-align: left !important;
    }
</style>
<div class="test_evaluation_outer" style="display: none" id="divcreate">

    <div class="process_end_popup">
        <center>
            <br />
            <p style="color: black; font-size: 24px">Creating Section..</p>
            <img width="128" src="@("/content/images/notloader.gif")" alt="Loading" id="img3" />

            <br />
            <br />
        </center>
    </div>

</div>
<div class="test_evaluation_outer" style="display: none" id="divupdate">

    <div class="process_end_popup">
        <center>
            <br />
            <p style="color: black; font-size: 24px">Updating Section..</p>
            <img width="128" src="@("/content/images/notloader.gif")" alt="Loading" id="img3" />

            <br />
            <br />
        </center>
    </div>

</div>
<div class="test_evaluation_outer" style="display: none" id="divdelete">

    <div class="process_end_popup">
        <center>
            <br />
            <p style="color: black; font-size: 24px">Removing Section..</p>
            <img width="128" src="@("/content/images/notloader.gif")" alt="Loading" id="img3" />

            <br />
            <br />
        </center>
    </div>

</div>
<div class="test_evaluation_outer" style="display: none" id="divload">

    <div class="process_end_popup">
        <center>
            <br />
            <p style="color: black; font-size: 24px">Loading..</p>
            <img width="128" src="@("/content/images/notloader.gif")" alt="Loading" id="img3" />

            <br />
            <br />
        </center>
    </div>

</div>
<div class="create_wrap">
    <div class="batch_wrap" style="margin-top: 2px">
        <div class="top_h">
            <h2 id="CreateTitleH2">

                Section Listing

            </h2>
            @Html.ActionLink("<< Back to Dashboard", actionName: "Index", controllerName: "Home", routeValues: null, htmlAttributes: new { @class = "dashboard_btn loadanim" })

        </div>
    </div>

    <table style="width: 100%;">
        <tr>
            <td>
                <ul id="wizHeader">

                    <li>@Html.ActionLink("Step 1: Configure Test", "Edit", "Test", new { eid = Session["examid"].ToString() }, new { @title = "Step 1: Configure Test", @class = "nextStep loadanim" })</li>
                    <li><a title="Step 2: Configure Sections" class="currentStep">Step 2: Configure Sections</a> </li>
                    <li><a title="Step 2: Add Questions">Step 3: Add Questions</a> </li>
                    <li><a title="Step 4: Master Settings" class="nextStep">Step 4: Master Settings</a> </li>
                    <li><a title="Step 5: Preview Test" class="nextStep">Step 5: Preview Test</a> </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                <div id="seclisting">
                    <label class="tst_lable">

                        Test Sections:

                    </label>

                    <div class="prgme check_language">
                        <div style="width: 100%; margin-left: 4px;" class="tst_lable">
                            Add a section:
                            @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <span class="validerror">@ViewBag.ErrorMessage</span>
                            }
                            @using (Html.BeginForm("Create", "Sections", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()


                                List<SelectListItem> listItems = new List<SelectListItem>();
                                listItems.Add(new SelectListItem
                                {
                                    Text = "Select",
                                    Value = "",
                                    Selected = true
                                });
                                listItems.Add(new SelectListItem
                                {
                                    Text = "MCQ",
                                    Value = "1",

                                });

                                listItems.Add(new SelectListItem
                                {
                                    Text = "Essay",
                                    Value = "6"
                                });


                                @Html.DropDownList("ddlsections", new SelectList(listItems, "Value", "Text"), new { @class = "ginput", @style = "width:200px;" })

                                <input type="submit" class="up_savebtn" style="border: none; cursor: pointer; font-size: 16px;" value="Add Section" OnClientClick="javascript: return comp();" CssClass="up_savebtn" id="FinishButton" name="FinishButton" />
                                @*<asp:Button Visible="false" Style="border: none; cursor: pointer;float:right; font-size: 16px;" Text="Section Re-Ordering" OnClientClick="javascript: return load();" CssClass="up_savebtn" ID="Button4" OnClick="Button4_Click" />*@
                            }


                            <table class="creation_listing" rules="all" id="grdviewselected" style="width:100%;border-collapse:collapse;" cellspacing="0" border="1">
                                <tbody>
                                    <tr class="borderbottom" style="background-color:WhiteSmoke;height:50px;">
                                        <th scope="col" align="left">Sno</th>
                                        <th scope="col" align="left">Section Name</th>
                                        <th scope="col" align="left">Type</th>
                                        <th scope="col" align="center">Status</th>
                                        <th scope="col" align="center">Action</th>
                                    </tr>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td style="width:10%;" align="left">
                                                @Html.DisplayFor(modelItem => item.sectionid)
                                            </td>
                                            <td style="width:30%;" align="left">
                                                <span style="font-weight: 300">@Html.DisplayFor(modelItem => item.sectionname)</span>
                                            </td>
                                            <td style="width:15%;" align="left">
                                                <span style="font-weight: 300">@Html.DisplayFor(modelItem => item.type)</span>
                                            </td>
                                            <td style="width:10%;" align="left">

                                                @if (item.sectionname == "-----")
                                                {
                                                    <span id="status" style="font-weight: 300;" class="validerror">Unconfigured</span>
                                                }
                                                else
                                                {
                                                    <span id="status" style="font-weight: 300">Configured</span>
                                                }

                                            </td>
                                            <td style="width:10%;" align="left">


                                                @Html.ActionLink("Edit", actionName: "Edit", controllerName: "Sections", routeValues: new { eid = item.examid, secid = item.secid }, htmlAttributes: new { @class = "exdlt_uesr loadanim", @style = "border: none; cursor: pointer;" })
                                                <input name="delsec" value="Remove" onclick="javascript: return deleteCheck();" id="delsec" class="dlt_uesr" style="border: none; cursor: pointer;" type="submit">
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>


                        </div>
                    </div>
                </div>

            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: right">

                @if (ViewBag.NextButton == true)
                {
                    @Html.ActionLink("Next", actionName: "mcqlisting", controllerName: "Questions", routeValues: new { eid = Session["examid"].ToString(), secid = 1 }, htmlAttributes: new { @onclick = "javascript: return load();", @class = "crt_tset_btn loadanim actionbtns"})

                }
                @Html.ActionLink("Cancel", actionName: "Listing", controllerName: "Home", routeValues: null, htmlAttributes: new { @onclick = "javascript: return load();", @class = "crt_tset_btn loadanim cancelbtn" })




            </td>
        </tr>
    </table>
</div>