mmtMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mmtMVC.Models;

namespace mmtMVC.Controllers
{
    public class HomeController : Controller
    {
        private MMT_ConstEntities db = new MMT_ConstEntities();

        // GET: Home
        public ActionResult Index(string sortOrder, string currentFilter, string searchString)
        {
            


            ViewBag.CurrentSort = sortOrder;
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "examid_asc" : "";
            ViewBag.MasterSortParm = sortOrder == "uploaddate_desc" ? "uploaddate_asc" : "uploaddate_desc";
            ViewBag.NameSortParm = sortOrder == "examname_desc" ? "examname_asc" : "examname_desc";

            var c = (from e in db.mmtexams where e.addedby==2 select e).AsEnumerable();

            if (!String.IsNullOrEmpty(searchString))
            {
                c = c.Where(s => s.examname.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "examid_asc":
                    c = c.OrderBy(s => s.examid);
                    break;
                case "uploaddate_desc":
                    c = c.OrderBy(s => s.uploaddate);
                    break;
                case "examname_desc":
                    c = c.OrderByDescending(s => s.examname);
                    break;
                default:
                    c = c.OrderByDescending(s => s.examid);
                    break;
            }

            IList<TestList> results = c.Select(x => new TestList()
            {
                examid = x.examid,
                examname = x.examname,
                randomques = x.randomtest ?? false,
                uploaddate = x.uploaddate,
                FlagInfo = (from r in db.mmtexamflags where r.examid == x.examid select r).Select(t => new FlagInfo()
                {
                    flagerror = t.flagerror,
                    flagcount = t.flagcount ?? 0,
                }).ToList()

            }).ToList();
           
            return View(results.ToList());
        }
    }
}

mmtMVC/Controllers/TestController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mmtMVC.Models;
using System.Data.Entity.Validation;
using System.IO;
using System.Xml;
using mmtMVC.Utils;

namespace mmtMVC.Controllers
{
    public class TestController : Controller
    {
        private MMT_ConstEntities db = new MMT_ConstEntities();

        // GET: Test
        public ActionResult Index()
        {
            return View(db.mmtexams.ToList());
        }

        // GET: Test/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mmtexam mmtexam = db.mmtexams.Find(id);
            if (mmtexam == null)
            {
                return HttpNotFound();
            }
            return View(mmtexam);
        }

        // GET: Test/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Test/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(mmtexam mmtexam)
        {
            string logopath = "";
            string varnumbering = "0";
            if (ModelState.IsValid)
            {

                if (mmtexam.islogo == true)
                {
                    if (mmtexam.File != null)
                    {
                        HttpPostedFileBase quesimage = mmtexam.File;
                        if (quesimage.ContentLength != 0)
                        {
                            var fileNameques = Path.GetFileName(quesimage.FileName);
                            string typeques = Path.GetExtension(quesimage.FileName);
                            string path1 = System.Web.HttpContext.Current.Server.MapPath("/");
                            string logname = "img_2_" + typeques;
                            string fullpath = path1 + "/testlogo/" + logname;
                            quesimage.SaveAs(fullpath);
                            logopath = "testlogo/" + logname;
                        }
                    }
                    else
                    {
                        return View();
                    }
                }

                XmlDocument xmldocMaster = new XmlDocument();
                XmlDocument xmldoc = new XmlDocument();

                XmlElement xmlRoot, newelementtest;

                XmlDeclaration declaration = xmldoc.CreateXmlDeclaration("1.0", "utf-8", null);
                xmldoc.AppendChild(declaration);
                xmldoc.AppendChild(xmldoc.CreateElement("", "Customexam", ""));
                xmlRoot = xmldoc.DocumentElement;


                newelementtest = xmldoc.CreateElement("test");

                XmlElement vartest = xmldoc.CreateElement("Numbering");
                vartest.InnerText = varnumbering;
                newelementtest.AppendChild(vartest);

                XmlElement varreview = xmldoc.CreateElement("Review");
                varreview.InnerText = "";

                XmlAttribute indvidual = xmldoc.CreateAttribute("individual");
                indvidual.Value = "1";
                varreview.Attributes.Append(indvidual);

                XmlAttribute typemain = xmldoc.CreateAttribute("type");
                typemain.Value = "";
                varreview.Attributes.Append(typemain);

                XmlAttribute showmain = xmldoc.CreateAttribute("show");
                showmain.Value = "1";
                varreview.Attributes.Append(showmain);

                newelementtest.AppendChild(varreview);

                XmlElement vartimes = xmldoc.CreateElement("Time");
                vartimes.InnerText = "";
                newelementtest.AppendChild(vartimes);

                XmlAttribute timttype = xmldoc.CreateAttribute("show");
                timttype.Value = "1";

                vartimes.Attributes.Append(timttype);

                XmlElement varqueslevel = xmldoc.CreateElement("QuestionRatio");
                varqueslevel.InnerText = "";
                newelementtest.AppendChild(varqueslevel);

                XmlAttribute status = xmldoc.CreateAttribute("status");
                status.Value = "";
                varqueslevel.Attributes.Append(status);

                XmlAttribute quescounttype = xmldoc.CreateAttribute("quescounttype");
                quescounttype.Value = "1";
                varqueslevel.Attributes.Append(quescounttype);

                XmlAttribute level1 = xmldoc.CreateAttribute("level1");
                level1.Value = Request["ratio1"];
                varqueslevel.Attributes.Append(level1);

                XmlAttribute level2 = xmldoc.CreateAttribute("level2");
                level2.Value = Request["ratio2"];
                varqueslevel.Attributes.Append(level2);

                XmlAttribute level3 = xmldoc.CreateAttribute("level3");
                level3.Value = Request["ratio3"];
                varqueslevel.Attributes.Append(level3);

                XmlAttribute questioncount = xmldoc.CreateAttribute("questioncount");
                questioncount.Value = Request["totques"];
                varqueslevel.Attributes.Append(questioncount);

                XmlElement newelement1 = xmldoc.CreateElement("sections");
                newelement1.InnerText = "";
                newelementtest.AppendChild(newelement1);

                XmlElement questions = xmldoc.CreateElement("questions");
                questions.InnerText = "";
                newelementtest.AppendChild(questions);

                xmldoc.DocumentElement.AppendChild(newelementtest);


                mmtexam.uploaddate = DateTime.UtcNow.AddHours(5.5);
                mmtexam.catid = 99;
                mmtexam.addedby = 2;
                mmtexam.islive = false;
                mmtexam.passingmarks = 50;
                mmtexam.examlanguage = "English";
                mmtexam.masterxmlfile = xmldoc.OuterXml;
                mmtexam.path = logopath;
                db.mmtexams.Add(mmtexam);

                try
                {

                    db.SaveChanges();
                    int id = mmtexam.examid;

                    Utils.CACheckXML.CheckXML(id);


                    return RedirectToAction("Listing","Sections", new {eid= id });
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw;
                }
             
            }
            else
            {
                return View();
            }


           
        }

        // GET: Test/Edit/5
        public ActionResult Edit(int? eid)
        {
            if (eid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mmtexam mmtexam = db.mmtexams.Find(eid);
            if (mmtexam == null)
            {
                return HttpNotFound();
            }
            return View(mmtexam);
        }

        // POST: Test/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(mmtexam mmtexam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mmtexam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mmtexam);
        }

        // GET: Test/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mmtexam mmtexam = db.mmtexams.Find(id);
            if (mmtexam == null)
            {
                return HttpNotFound();
            }
            return View(mmtexam);
        }

        // POST: Test/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            mmtexam mmtexam = db.mmtexams.Find(id);
            db.mmtexams.Remove(mmtexam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mmtMVC/Views/Home/Index.cshtml
@model IEnumerable<mmtMVC.Models.TestList>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


<div class="table_demo_wrapper">
    <div class="batch_wrap" style="margin-top: 20px">
        <div class="top_h">
            <h2>Dashboard</h2>
        </div>

        @Html.ActionLink("Create New Test", "Create","Test", null, new { @style = "margin-top: 15px; float: left; font-size: 15px;", @class = "new_test_btn loadanim" })
        @*<a class="new_test_btn" style="margin-top: 15px; float: left; font-size: 15px;" href="addtest.aspx">Create New Test</a>
            <%if (downloadexam == true)
            {

            %>
            <a class="new_test_btn" style="margin-top: 15px; float: right; font-size: 15px;" href="exceldownload.aspx">Download Exam</a>
            <%
            }

            if (ispool == true)
            {

            %>         <a class="new_test_btn" style="margin-top: 15px; float: right; font-size: 15px;" href="mcqlisting.aspx">Manage Pool Questions</a>

            <a style="margin-top: 15px; float: right; font-size: 15px" class="new_test_btn" href="ExcelPoolUpload.aspx">Upload Question to Pool</a>

            <a style="margin-top: 15px; float: right; font-size: 15px" class="new_test_btn" href="createpoolquestion.aspx">Create New Pool Question</a>
            <a style="margin-top: 15px; float: right; font-size: 15px" class="new_test_btn" href="createpoolexam.aspx">Create New Pool</a>
            <%}


            if (ispool == false && ispoolx == true)
            {

            %>
            <a class="new_test_btn" style="margin-top: 15px; float: right; font-size: 15px;" href="mcqlisting.aspx">Manage Pool Questions</a>
            <%} %>*@


    </div>

    <div class="table_txt" style="margin-bottom: 50px; margin-top: 15px">
        <div class="shoring_top">
            <div class="short_type">
                @using (Html.BeginForm("Index", "", FormMethod.Get))
                {
                    @Html.Label("Search:")
                    @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "ddlClass" })
                    <input type="submit" value="Search" />


                }

            </div>
            <div class="short_type">
                @using (Html.BeginForm())
                {
                    <input style="margin-top: 13px; " type="submit" value="Reset" />}
            </div>

        </div>
        <div>

            <table class="dash-table1" width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody style="overflow-y: hidden;">
                    <tr>
                        <th scope="col" class="w2">
                            <span>
                                @Html.ActionLink("Test ID", "Index", new { sortOrder = ViewBag.IDSortParm, currentFilter = ViewBag.CurrentFilter })
                            </span>
                        </th>
                        <th scope="col" class="w3">
                            <span>
                                @Html.ActionLink("Date Created", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
                            </span>
                        </th>
                        <th scope="col" class="w4">
                            <span>
                                @Html.ActionLink("Test Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                            </span>
                        </th>


                        <th scope="col" class="w5">
                            @Html.ActionLink("Flagged", "Index", new { sortOrder = ViewBag.FlagParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        <th scope="col" class="w6">
                            Freeze <span>
                                <a href="javascript:void(0)" title="<span><ul style='padding-left: 7px;'><li>Freeze the test once you are satisfied that it is ready to go live.</li><li>The test cannot be freezed, if it has been flagged for discrepancies.<br /> Click <img src='@("/content/images/red-flag.png")' /> to the left to resolve.</li></ul></span>" data-alignx="center" data-alignto="target" data-aligny="top" data-offsety="5" data-offsetx="0" class="tooltipSetting tooltip2">
                                    <img src="@("/content/images/info-icon.png")" />
                                </a>
                            </span>
                        </th>
                        <th scope="col" class="w7">Actions</th>

                    </tr>
                </tbody>
            </table>
            <table class="creation_listing">
                @foreach (var item in Model)
            {

                    <tr style="background-color:WhiteSmoke;">
                        <td class="w2">
                            <span>@Html.DisplayFor(modelItem => item.examid)</span>
                        </td>
                        <td class="w3">
                            <span>@Html.DisplayFor(modelItem => item.uploaddate)</span>
                        </td>
                        <td class="leftpadding w4">
                            <div class="describe" style="text-align: left; width: 300px; padding-top: 17px;">
                                <h6>

                                    @Html.DisplayFor(modelItem => item.examname)
                                </h6>

                            </div>
                        </td>
                        <td class="w5">
                            @foreach (var flag in item.FlagInfo)
                            {
                                if (flag.flagcount > 0)
                                {
                                    <div id="redflag">
                                        <a href="javascript:openflags()" class="tooltip2">
                                            <img src="@("/content/images/red-flag.png")"/><span>Click to View</span>
                                        </a>
                                        @Html.DisplayFor(modelItem => flag.flagcount)
                                    </div>
                                }
                                else
                                {
                                    <div id="greenflag">
                                        <img src="@("/content/images/green-flag.png")" />
                                    </div>
                                }

                            }

                        </td>
                        <td class="w6">
                            <a id="ContentPlaceHolder1_grdExams_freeze_0" class="dash-freez" href="javascript:__doPostBack('ctl00$ContentPlaceHolder1$grdExams$ctl02$freeze','')"></a>
                        </td>
                        <td class="w7" valign="middle">
                            <div id="panel1">

                                <div style="float: left">
                                    @Html.ActionLink(" ",actionName:"Listing",controllerName:"Sections", routeValues: new { eid = item.examid }, htmlAttributes: new {@class= "tooltip2 dash-edit edit-users loadanim", @style= "padding-right:10px;" })
                                 
                                </div>
                                <div style="float: left">
                                </div>

                                <div id="publish" style="float:left;display:inline-block;">
                                    @*<a id="ContentPlaceHolder1_grdExams_LinkButton1_0" class="tooltip2 dash-publish" href="javascript:__doPostBack('ctl00$ContentPlaceHolder1$grdExams$ctl02$LinkButton1','')"><span>Publish Exam</span></a>*@
                                </div>
                            </div>
                        </td>
                    </tr>

                }
            </table>
        </div>
    </div>
</div>